[package]
name = "Wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "*"
rust-crypto = "*"
actix-web = "*"
actix-cors ="*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
env_logger = "*"
log = "*"
structopt = "*"